apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-final
data:
  APP_NAME: "Python Flask Ariadne API"
  FLASK_ENV: "production"
  FLASK_DEBUG_MODE: "false"
  FLASK_RUN_PORT: "5000"
  POSTGRES_DB: "pfaas_prod"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
